# Generated by Django 2.1.7 on 2019-04-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_userproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='career_opportunities_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='company_benefit_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='culture_values_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='overall_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='senior_management_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='work_balance_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
