# Generated by Django 2.1.7 on 2019-04-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20190419_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='uid',
        ),
    ]
