# Generated by Django 2.1.7 on 2019-04-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_remove_userproperties_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic_app.UserProfileInfo'),
        ),
    ]
